publish_to: none

name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  reify:
    path: ../packages/reify
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
