name: reify
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

dependencies:
  args: ^2.5.0
  vm_service: 14.0.0
  watcher: ^1.1.0
  stream_transform: ^2.1.0
  mark: ^0.3.0
  pure: ^0.2.0
  intl: ^0.19.0
  glob: ^2.1.2
  markdown: 7.2.1
  yaml: ^3.1.2

dev_dependencies:
  purple_lints: ^0.4.0
