publish_to: none

name: web_reify
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  reify:
    git:
      url: https://github.com/purplenoodlesoop/reify.git
      path: packages/reify
  markdown: ^7.2.2
  yaml: ^3.1.2
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  purple_lints: ^0.4.0
