name: reify
description: Declarative data processing for Dart.
version: 1.0.0
repository: https://github.com/purplenoodlesoop/reify/tree/master/packages/reify

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.5.0
  vm_service: ^14.3.1
  watcher: ^1.1.0
  stream_transform: ^2.1.0
  mark: ^0.3.0
  pure: ^0.2.0
  intl: ^0.19.0
  glob: ^2.1.2
  yaml: ^3.1.2
  path: ^1.9.0

dev_dependencies:
  purple_lints: ^0.4.0
